### ISSUE TITLE
How to change attribute for mmd and mmd-model components?

### ISSUE THREAD

**Issue by kurai021** [takahirox/a-mmd#1]
I want to know the proper way to change a mmd attribute and mmd-model with a HTML select, I can't with setAttribute and removeAttribute at the second select change.

**Comment by takahirox** [comment]
Let me check...

**Comment by kurai021** [comment]
Hi, I have made a example, you can check ar_vocaloid demo in my repository https://github.com/kurai021/aframe_demos but I should disable THREE.cache in aframe.js to reuse sounds and vmd files. This is a problem for connections although prevent to save in memory (and occupy a lot of RAM)
